import { ReportDefinition } from './report-types';

import {
  executeStudentDirectoryReport,
  executeEnrollmentSummaryReport,
  executeStudentDemographicsReport,
} from './queries/student-reports';

import {
  executeResultSummaryReport,
  executeSubjectPerformanceReport,
  executeClassPerformanceReport,
  executeStudentPerformanceReport,
  executeAtRiskStudentsReport,
} from './queries/academic-reports';

import {
  executeDailyAttendanceReport,
  executeMonthlyAttendanceReport,
  executeStudentAttendanceSummaryReport,
  executeEmployeeAttendanceSummaryReport,
  executeAttendanceExceptionsReport,
} from './queries/attendance-reports';

import {
  executeFeeCollectionReport,
  executeOutstandingAgingReport,
  executePaymentMethodsReport,
  executeStudentLedgerReport,
  executeDiscountsReport,
} from './queries/finance-reports';

import {
  executeEmployeeDirectoryReport,
  executeDepartmentSummaryReport,
  executePayrollSummaryReport,
  executeSalaryAdvanceReport,
} from './queries/hr-reports';

import { executeAdmissionFunnelReport } from './queries/admission-reports';
import { executeTransportUtilizationReport, executeTransportBoardingReport } from './queries/transport-reports';
import { executeLibraryCirculationReport, executePopularBooksReport, executeLibraryFinesReport } from './queries/library-reports';
import { executeInventoryStockSummaryReport, executeAssetRegisterValuationReport } from './queries/inventory-reports';

/**
 * Authoritative Typed Registry of all reports in EduSmart BD.
 */
export const REPORT_REGISTRY: Record<string, ReportDefinition> = {
  // ==========================================
  // MODULE: STUDENTS
  // ==========================================
  student_directory: {
    reportId: 'student_directory',
    name: 'Student Directory',
    nameBn: 'শিক্ষার্থী নির্দেশিকা',
    module: 'STUDENTS',
    description: 'Comprehensive roster of enrolled students with campus, class, section, and roll.',
    descriptionBn: 'ক্যাম্পাস, শ্রেণি, শাখা ও রোলসহ ভর্তি হওয়া শিক্ষার্থীদের সামগ্রিক তালিকা।',
    requiredPermission: 'REPORTS_STUDENTS_VIEW',
    supportedFilters: ['academicSessionId', 'campusId', 'classId', 'sectionId', 'gender', 'status'],
    supportedExports: ['CSV', 'XLSX', 'PDF', 'PRINT'],
    defaultSort: { field: 'rollNumber', order: 'ASC' },
    execute: executeStudentDirectoryReport,
  },
  student_enrollment_summary: {
    reportId: 'student_enrollment_summary',
    name: 'Enrollment Status Summary',
    nameBn: 'ভর্তি অবস্থার সারসংক্ষেপ',
    module: 'STUDENTS',
    description: 'Breakdown of new admissions, promotions, transfers, and retention rates.',
    descriptionBn: 'নতুন ভর্তি, প্রমোশন, ট্রান্সফার ও ধরে রাখার হারের তথ্য।',
    requiredPermission: 'REPORTS_STUDENTS_VIEW',
    supportedFilters: ['academicSessionId', 'campusId', 'classId'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'className', order: 'ASC' },
    execute: executeEnrollmentSummaryReport,
  },
  student_demographics: {
    reportId: 'student_demographics',
    name: 'Student Demographics',
    nameBn: 'শিক্ষার্থী জনমিতি',
    module: 'STUDENTS',
    description: 'Institutional breakdown by gender, blood group, and campus location.',
    descriptionBn: 'লিঙ্গ, রক্তের গ্রুপ এবং ক্যাম্পাসভিত্তিক শিক্ষার্থীদের পরিসংখ্যান।',
    requiredPermission: 'REPORTS_STUDENTS_VIEW',
    supportedFilters: ['academicSessionId', 'campusId'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'metric', order: 'ASC' },
    execute: executeStudentDemographicsReport,
  },

  // ==========================================
  // MODULE: ACADEMICS
  // ==========================================
  academic_result_summary: {
    reportId: 'academic_result_summary',
    name: 'Exam Result Summary',
    nameBn: 'পরীক্ষার ফলাফলের সারসংক্ষেপ',
    module: 'ACADEMICS',
    description: 'Class-wise examinee counts, pass rates, fail rates, and average GPAs.',
    descriptionBn: 'শ্রেণিভিত্তিক পরীক্ষার্থী সংখ্যা, পাসের হার, ফেলের হার এবং গড় জিপিএ।',
    requiredPermission: 'REPORTS_ACADEMICS_VIEW',
    supportedFilters: ['examId', 'classId', 'sectionId'],
    supportedExports: ['CSV', 'XLSX', 'PDF', 'PRINT'],
    defaultSort: { field: 'className', order: 'ASC' },
    execute: executeResultSummaryReport,
  },
  academic_subject_performance: {
    reportId: 'academic_subject_performance',
    name: 'Subject Performance Analysis',
    nameBn: 'বিষয়ভিত্তিক ফলাফল বিশ্লেষণ',
    module: 'ACADEMICS',
    description: 'Highest, lowest, and average marks with pass percentage per subject.',
    descriptionBn: 'প্রতি বিষয়ে সর্বোচ্চ, সর্বনিম্ন এবং গড় নম্বরসহ পাসের হার।',
    requiredPermission: 'REPORTS_ACADEMICS_VIEW',
    supportedFilters: ['examId', 'subjectId'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'subjectName', order: 'ASC' },
    execute: executeSubjectPerformanceReport,
  },
  academic_class_performance: {
    reportId: 'academic_class_performance',
    name: 'Class Comparison Report',
    nameBn: 'শ্রেণিভিত্তিক তুলনামূলক প্রতিবেদন',
    module: 'ACADEMICS',
    description: 'Comparative performance and GPA 5.00 distribution across classes.',
    descriptionBn: 'বিভিন্ন শ্রেণির মধ্যে ফলাফল ও জিপিএ ৫.০০ এর তুলনামূলক চিত্র।',
    requiredPermission: 'REPORTS_ACADEMICS_VIEW',
    supportedFilters: ['examId'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'className', order: 'ASC' },
    execute: executeClassPerformanceReport,
  },
  academic_student_performance: {
    reportId: 'academic_student_performance',
    name: 'Student Merit & Rank List',
    nameBn: 'শিক্ষার্থী মেধা তালিকা ও স্থান',
    module: 'ACADEMICS',
    description: 'Ranked list of students by total marks obtained and GPA in the exam.',
    descriptionBn: 'পরীক্ষায় প্রাপ্ত মোট নম্বর ও জিপিএ অনুযায়ী শিক্ষার্থীদের মেধা তালিকা।',
    requiredPermission: 'REPORTS_ACADEMICS_VIEW',
    supportedFilters: ['examId', 'classId', 'sectionId'],
    supportedExports: ['CSV', 'XLSX', 'PDF', 'PRINT'],
    defaultSort: { field: 'meritRank', order: 'ASC' },
    execute: executeStudentPerformanceReport,
  },
  academic_at_risk_students: {
    reportId: 'academic_at_risk_students',
    name: 'Academic At-Risk Students',
    nameBn: 'ঝুঁকিপূর্ণ শিক্ষার্থী তালিকা',
    module: 'ACADEMICS',
    description: 'Students requiring academic intervention based on failed subjects or low GPA.',
    descriptionBn: 'অনুত্তীর্ণ বিষয় বা নিম্ন জিপিএর কারণে বিশেষ তত্ত্বাবধান প্রয়োজন এমন শিক্ষার্থী।',
    requiredPermission: 'REPORTS_ACADEMICS_VIEW',
    supportedFilters: ['examId', 'classId', 'sectionId'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'failedSubjects', order: 'DESC' },
    execute: executeAtRiskStudentsReport,
  },

  // ==========================================
  // MODULE: ATTENDANCE
  // ==========================================
  attendance_daily_summary: {
    reportId: 'attendance_daily_summary',
    name: 'Daily Attendance Summary',
    nameBn: 'দৈনিক উপস্থিতির সারসংক্ষেপ',
    module: 'ATTENDANCE',
    description: 'Daily student attendance rates, present, absent, late, and excused counts.',
    descriptionBn: 'দৈনিক শিক্ষার্থী উপস্থিতির হার, উপস্থিত, অনুপস্থিত ও বিলম্বে আগমনের হিসাব।',
    requiredPermission: 'REPORTS_ATTENDANCE_VIEW',
    supportedFilters: ['startDate', 'classId', 'sectionId'],
    supportedExports: ['CSV', 'XLSX', 'PDF', 'PRINT'],
    defaultSort: { field: 'className', order: 'ASC' },
    execute: executeDailyAttendanceReport,
  },
  attendance_monthly_summary: {
    reportId: 'attendance_monthly_summary',
    name: 'Monthly Attendance Trend',
    nameBn: 'মাসিক উপস্থিতির ধারা',
    module: 'ATTENDANCE',
    description: 'Daily trend line of student attendance across the selected date range.',
    descriptionBn: 'নির্দিষ্ট সময়কালে প্রতিদিনের শিক্ষার্থী উপস্থিতির পরিবর্তনের হার।',
    requiredPermission: 'REPORTS_ATTENDANCE_VIEW',
    supportedFilters: ['startDate', 'endDate', 'classId'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'date', order: 'ASC' },
    execute: executeMonthlyAttendanceReport,
  },
  attendance_student_summary: {
    reportId: 'attendance_student_summary',
    name: 'Student Attendance Register',
    nameBn: 'শিক্ষার্থী উপস্থিতি খাতা',
    module: 'ATTENDANCE',
    description: 'Aggregated working days, present days, and attendance rates per student.',
    descriptionBn: 'প্রতি শিক্ষার্থীর মোট কার্যদিবস, উপস্থিতি এবং উপস্থিতির হারের বিবরণ।',
    requiredPermission: 'REPORTS_ATTENDANCE_VIEW',
    supportedFilters: ['startDate', 'endDate', 'classId', 'sectionId'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'studentCode', order: 'ASC' },
    execute: executeStudentAttendanceSummaryReport,
  },
  attendance_employee_summary: {
    reportId: 'attendance_employee_summary',
    name: 'Staff Attendance Register',
    nameBn: 'কর্মচারী উপস্থিতি রেজিস্টার',
    module: 'ATTENDANCE',
    description: 'Attendance statistics for teachers and staff members over the date range.',
    descriptionBn: 'শিক্ষক ও কর্মচারীদের মোট কার্যদিবস, উপস্থিতি ও ছুটির বিবরণী।',
    requiredPermission: 'REPORTS_ATTENDANCE_VIEW',
    supportedFilters: ['startDate', 'endDate'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'code', order: 'ASC' },
    execute: executeEmployeeAttendanceSummaryReport,
  },
  attendance_exceptions: {
    reportId: 'attendance_exceptions',
    name: 'Absence & Late Arrivals',
    nameBn: 'অনুপস্থিতি ও বিলম্বের তালিকা',
    module: 'ATTENDANCE',
    description: 'Detailed roster of students who were absent or arrived late with documented reasons.',
    descriptionBn: 'অনুপস্থিত বা বিলম্বে আগত শিক্ষার্থীদের কারণসহ বিস্তারিত তালিকা।',
    requiredPermission: 'REPORTS_ATTENDANCE_VIEW',
    supportedFilters: ['startDate', 'classId', 'sectionId'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'status', order: 'ASC' },
    execute: executeAttendanceExceptionsReport,
  },

  // ==========================================
  // MODULE: FINANCE
  // ==========================================
  finance_fee_collection: {
    reportId: 'finance_fee_collection',
    name: 'Fee Collection Register',
    nameBn: 'ফি আদায়ের রেজিস্টার',
    module: 'FINANCE',
    description: 'Itemized fee collections by date, receipt number, student, and payment method.',
    descriptionBn: 'তারিখ, রশিদ নম্বর, শিক্ষার্থী ও পরিশোধের মাধ্যম অনুযায়ী আদায়কৃত ফির বিবরণ।',
    requiredPermission: 'REPORTS_FINANCE_VIEW',
    supportedFilters: ['startDate', 'endDate', 'paymentStatus'],
    supportedExports: ['CSV', 'XLSX', 'PDF', 'PRINT'],
    defaultSort: { field: 'paymentDate', order: 'DESC' },
    execute: executeFeeCollectionReport,
  },
  finance_outstanding_aging: {
    reportId: 'finance_outstanding_aging',
    name: 'Receivables Aging Report',
    nameBn: 'বকেয়া মেয়াদের প্রতিবেদন',
    module: 'FINANCE',
    description: 'Institutional receivables categorized into aging buckets (0-30, 31-60, 61-90, 90+ days).',
    descriptionBn: 'বকেয়া ফির বয়স অনুযায়ী বিভাগ (০-৩০ দিন, ৩১-৬০ দিন, ৬১-৯০ দিন, ৯০+ দিন)।',
    requiredPermission: 'REPORTS_FINANCE_VIEW',
    supportedFilters: ['academicSessionId', 'studentId'],
    supportedExports: ['CSV', 'XLSX', 'PDF', 'PRINT'],
    defaultSort: { field: 'daysOverdue', order: 'DESC' },
    execute: executeOutstandingAgingReport,
  },
  finance_payment_methods: {
    reportId: 'finance_payment_methods',
    name: 'Payment Channels Breakdown',
    nameBn: 'পেমেন্ট চ্যানেল বিশ্লেষণ',
    module: 'FINANCE',
    description: 'Collection volume and percentage share across cash, bKash, Nagad, and bank transfers.',
    descriptionBn: 'ক্যাশ, বিকাশ, নগদ এবং ব্যাংক স্থানান্তরের মাধ্যমে আদায়ের শতকরা হার।',
    requiredPermission: 'REPORTS_FINANCE_VIEW',
    supportedFilters: ['startDate', 'endDate'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'total', order: 'DESC' },
    execute: executePaymentMethodsReport,
  },
  finance_student_ledger: {
    reportId: 'finance_student_ledger',
    name: 'Student Financial Ledger',
    nameBn: 'শিক্ষার্থীর আর্থিক লেজার',
    module: 'FINANCE',
    description: 'Authoritative debit (fees) and credit (payments) transaction history with running balance.',
    descriptionBn: 'শিক্ষার্থীর ধার্যকৃত ফি ও পরিশোধের পূর্ণাঙ্গ ডেবিট/ক্রেডিট স্টেটমেন্ট।',
    requiredPermission: 'REPORTS_FINANCE_VIEW',
    supportedFilters: ['studentId'],
    supportedExports: ['CSV', 'XLSX', 'PDF', 'PRINT'],
    defaultSort: { field: 'date', order: 'ASC' },
    execute: executeStudentLedgerReport,
  },
  finance_discounts: {
    reportId: 'finance_discounts',
    name: 'Scholarships & Waivers',
    nameBn: 'বৃত্তি ও ছাড়ের প্রতিবেদন',
    module: 'FINANCE',
    description: 'Authorized fee concessions, waivers, and scholarships with recorded justifications.',
    descriptionBn: 'অনুমোদিত ফির ছাড়, মওকুফ ও মেধা বৃত্তির তথ্য।',
    requiredPermission: 'REPORTS_FINANCE_VIEW',
    supportedFilters: ['studentId'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'studentCode', order: 'ASC' },
    execute: executeDiscountsReport,
  },

  // ==========================================
  // MODULE: HR
  // ==========================================
  hr_employee_directory: {
    reportId: 'hr_employee_directory',
    name: 'Employee Directory',
    nameBn: 'কর্মকর্তা-কর্মচারী নির্দেশিকা',
    module: 'HR',
    description: 'Institutional staff directory categorized by department, designation, and campus.',
    descriptionBn: 'বিভাগ, পদবি ও ক্যাম্পাসভিত্তিক কর্মরত সকল কর্মকর্তা-কর্মচারীর তালিকা।',
    requiredPermission: 'REPORTS_HR_VIEW',
    supportedFilters: ['departmentId', 'campusId', 'status'],
    supportedExports: ['CSV', 'XLSX', 'PDF', 'PRINT'],
    defaultSort: { field: 'employeeCode', order: 'ASC' },
    execute: executeEmployeeDirectoryReport,
  },
  hr_department_summary: {
    reportId: 'hr_department_summary',
    name: 'Department Headcount',
    nameBn: 'বিভাগীয় জনবল সারসংক্ষেপ',
    module: 'HR',
    description: 'Staff allocation count and active employee distribution per department.',
    descriptionBn: 'প্রতি বিভাগে কর্মকর্তা-কর্মচারীদের সংখ্যা ও বণ্টন।',
    requiredPermission: 'REPORTS_HR_VIEW',
    supportedFilters: [],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'nameEn', order: 'ASC' },
    execute: executeDepartmentSummaryReport,
  },
  hr_payroll_summary: {
    reportId: 'hr_payroll_summary',
    name: 'Payroll Expenditure Summary',
    nameBn: 'বেতন ব্যয়ের সারসংক্ষেপ',
    module: 'HR',
    description: 'Historical finalized payroll expenditures, gross salaries, deductions, and net disbursements.',
    descriptionBn: 'চূড়ান্ত বেতন ব্যয়ের হিসাব, গ্রস বেতন, কর্তন এবং নিট প্রদান।',
    requiredPermission: 'REPORTS_HR_VIEW',
    supportedFilters: ['status'],
    supportedExports: ['CSV', 'XLSX', 'PDF', 'PRINT'],
    defaultSort: { field: 'periodMonth', order: 'DESC' },
    execute: executePayrollSummaryReport,
  },
  hr_salary_advance: {
    reportId: 'hr_salary_advance',
    name: 'Salary Advance Register',
    nameBn: 'অগ্রিম বেতন রেজিস্টার',
    module: 'HR',
    description: 'Employee salary advances issued, recovered through payroll, and remaining balances.',
    descriptionBn: 'প্রদত্ত অগ্রিম বেতন, আদায়কৃত অংশ এবং অবশিষ্ট বকেয়ার হিসাব।',
    requiredPermission: 'REPORTS_HR_VIEW',
    supportedFilters: ['status'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'employeeCode', order: 'ASC' },
    execute: executeSalaryAdvanceReport,
  },

  // ==========================================
  // MODULE: ADMISSIONS
  // ==========================================
  admission_funnel: {
    reportId: 'admission_funnel',
    name: 'Admission Funnel & Demand',
    nameBn: 'ভর্তি ফানেল ও চাহিদা বিশ্লেষণ',
    module: 'ADMISSIONS',
    description: 'Conversion rates from application to enrollment and demand by target class.',
    descriptionBn: 'আবেদন থেকে চূড়ান্ত ভর্তির রূপান্তর হার ও শ্রেণিভিত্তিক চাহিদার চিত্র।',
    requiredPermission: 'REPORTS_ADMISSIONS_VIEW',
    supportedFilters: ['academicSessionId', 'campusId', 'classId'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'className', order: 'ASC' },
    execute: executeAdmissionFunnelReport,
  },

  // ==========================================
  // MODULE: TRANSPORT
  // ==========================================
  transport_utilization: {
    reportId: 'transport_utilization',
    name: 'Route & Fleet Utilization',
    nameBn: 'রুট ও যানবাহন ব্যবহার প্রতিবেদন',
    module: 'TRANSPORT',
    description: 'Active transport routes, assigned student counts, and fleet capacity utilization.',
    descriptionBn: 'সক্রিয় পরিবহন রুট, নিবন্ধিত শিক্ষার্থী সংখ্যা এবং যানবাহনের সক্ষমতা।',
    requiredPermission: 'REPORTS_TRANSPORT_VIEW',
    supportedFilters: ['campusId'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'routeCode', order: 'ASC' },
    execute: executeTransportUtilizationReport,
  },
  transport_boarding: {
    reportId: 'transport_boarding',
    name: 'Boarding & No-Show Log',
    nameBn: 'বোর্ডিং ও অনুপস্থিতির লগ',
    module: 'TRANSPORT',
    description: 'Daily student boarding events, missed pickups, and dropoff logs.',
    descriptionBn: 'দৈনিক শিক্ষার্থী বাসে ওঠা, নামা এবং অনুপস্থিতির বিস্তারিত লগ।',
    requiredPermission: 'REPORTS_TRANSPORT_VIEW',
    supportedFilters: ['startDate'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'time', order: 'DESC' },
    execute: executeTransportBoardingReport,
  },

  // ==========================================
  // MODULE: LIBRARY
  // ==========================================
  library_circulation: {
    reportId: 'library_circulation',
    name: 'Circulation & Active Loans',
    nameBn: 'বই ইস্যু ও সক্রিয় ঋণের তালিকা',
    module: 'LIBRARY',
    description: 'Currently issued books, student and staff borrowers, due dates, and return statuses.',
    descriptionBn: 'বর্তমান ইস্যুকৃত বই, শিক্ষার্থী ও কর্মচারীদের ঋণ বিবরণ এবং ফেরতের তারিখ।',
    requiredPermission: 'REPORTS_LIBRARY_VIEW',
    supportedFilters: ['status'],
    supportedExports: ['CSV', 'XLSX', 'PDF', 'PRINT'],
    defaultSort: { field: 'issueDate', order: 'DESC' },
    execute: executeLibraryCirculationReport,
  },
  library_popular_titles: {
    reportId: 'library_popular_titles',
    name: 'Most Borrowed Books',
    nameBn: 'সর্বাধিক পঠিত বইয়ের তালিকা',
    module: 'LIBRARY',
    description: 'Top circulated book titles, total catalog copies, and borrow counts.',
    descriptionBn: 'গ্রন্থাগারে সবচেয়ে বেশি ধার নেওয়া বই ও কপি সংখ্যা।',
    requiredPermission: 'REPORTS_LIBRARY_VIEW',
    supportedFilters: [],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'borrowCount', order: 'DESC' },
    execute: executePopularBooksReport,
  },
  library_fines: {
    reportId: 'library_fines',
    name: 'Library Fines & Penalties',
    nameBn: 'গ্রন্থাগার জরিমানা রেজিস্টার',
    module: 'LIBRARY',
    description: 'Overdue, lost book, and damage fines assessed, paid, and outstanding.',
    descriptionBn: 'বিলম্বে ফেরত বা ক্ষতিগ্রস্ত বইয়ের জরিমানা ও আদায়ের হিসাব।',
    requiredPermission: 'REPORTS_LIBRARY_VIEW',
    supportedFilters: ['status'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'amount', order: 'DESC' },
    execute: executeLibraryFinesReport,
  },

  // ==========================================
  // MODULE: INVENTORY & ASSETS
  // ==========================================
  inventory_stock_summary: {
    reportId: 'inventory_stock_summary',
    name: 'Stock Valuation & Reorder Alerts',
    nameBn: 'মজুদ পণ্যের মূল্য ও সতর্কতা',
    module: 'INVENTORY',
    description: 'Authoritative stock levels derived from movement ledger, current valuation, and low stock warnings.',
    descriptionBn: 'মুভমেন্ট লেজার থেকে প্রাপ্ত আসল মজুদ, বর্তমান বাজারমূল্য এবং স্বল্প মজুদের অ্যালার্ট।',
    requiredPermission: 'REPORTS_INVENTORY_VIEW',
    supportedFilters: ['campusId', 'inventoryCategoryId'],
    supportedExports: ['CSV', 'XLSX', 'PRINT'],
    defaultSort: { field: 'currentStock', order: 'ASC' },
    execute: executeInventoryStockSummaryReport,
  },
  asset_register_valuation: {
    reportId: 'asset_register_valuation',
    name: 'Capital Asset Register',
    nameBn: 'মূলধনী সম্পদ রেজিস্টার',
    module: 'INVENTORY',
    description: 'Tracked school capital assets, condition ratings, user assignments, and maintenance expenditures.',
    descriptionBn: 'প্রতিষ্ঠানের স্থায়ী সম্পদ, অবস্থা, ব্যবহারকারী এবং মেরামত খরচের বিবরণ।',
    requiredPermission: 'REPORTS_INVENTORY_VIEW',
    supportedFilters: ['campusId', 'status'],
    supportedExports: ['CSV', 'XLSX', 'PDF', 'PRINT'],
    defaultSort: { field: 'assetCode', order: 'ASC' },
    execute: executeAssetRegisterValuationReport,
  },
};
